services:
  postgres:
    image: postgres:16-alpine
    container_name: karma_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: karma
      POSTGRES_PASSWORD: karma_secret
      POSTGRES_DB: karmadb
    ports:
      - "5432:5432"
    volumes:
      - karma_pgdata:/var/lib/postgresql/data

volumes:
  karma_pgdata:
