-- AlterTable
ALTER TABLE "User" ADD COLUMN "karmaCoins" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN "lastCoinReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "subscriptionType" TEXT NOT NULL DEFAULT 'free',
ADD COLUMN "subscriptionExpiry" TIMESTAMP(3);
